onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -expand -group testbench /interrupt_regs_tb/clk
add wave -noupdate -expand -group testbench /interrupt_regs_tb/rst_i
add wave -noupdate -expand -group testbench -radix hexadecimal /interrupt_regs_tb/int_i
add wave -noupdate -expand -group testbench /interrupt_regs_tb/adr_i
add wave -noupdate -expand -group testbench -radix hexadecimal /interrupt_regs_tb/dat_i
add wave -noupdate -expand -group testbench -radix hexadecimal /interrupt_regs_tb/dat_o
add wave -noupdate -expand -group testbench /interrupt_regs_tb/we_i
add wave -noupdate -expand -group testbench /interrupt_regs_tb/en_i
add wave -noupdate -expand -group testbench /interrupt_regs_tb/irq_o
add wave -noupdate -expand -group regs /interrupt_regs_tb/regs/rst_i
add wave -noupdate -expand -group regs /interrupt_regs_tb/regs/clk_i
add wave -noupdate -expand -group regs -radix hexadecimal /interrupt_regs_tb/regs/int_i
add wave -noupdate -expand -group regs /interrupt_regs_tb/regs/adr_i
add wave -noupdate -expand -group regs -radix hexadecimal /interrupt_regs_tb/regs/dat_i
add wave -noupdate -expand -group regs -radix hexadecimal /interrupt_regs_tb/regs/dat_o
add wave -noupdate -expand -group regs /interrupt_regs_tb/regs/we_i
add wave -noupdate -expand -group regs /interrupt_regs_tb/regs/en_i
add wave -noupdate -expand -group regs /interrupt_regs_tb/regs/irq_o
add wave -noupdate -expand -group regs -radix hexadecimal /interrupt_regs_tb/regs/ICR
add wave -noupdate -expand -group regs -radix hexadecimal /interrupt_regs_tb/regs/IMR
add wave -noupdate -expand -group regs -radix hexadecimal /interrupt_regs_tb/regs/ITR
add wave -noupdate -expand -group regs -radix hexadecimal /interrupt_regs_tb/regs/IER
add wave -noupdate -expand -group regs -radix hexadecimal /interrupt_regs_tb/regs/irq
add wave -noupdate -expand -group regs /interrupt_regs_tb/regs/icr_we
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(31)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(31)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(31)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(31)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(31)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(31)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(31)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(31)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(31)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(31)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(31)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(31)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(31)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(31)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(31)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(31)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(30)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(30)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(30)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(30)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(30)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(30)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(30)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(30)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(30)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(30)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(30)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(30)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(30)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(30)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(30)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(30)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(29)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(29)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(29)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(29)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(29)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(29)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(29)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(29)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(29)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(29)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(29)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(29)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(29)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(29)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(29)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(29)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(28)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(28)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(28)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(28)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(28)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(28)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(28)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(28)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(28)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(28)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(28)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(28)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(28)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(28)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(28)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(28)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(27)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(27)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(27)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(27)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(27)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(27)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(27)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(27)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(27)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(27)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(27)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(27)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(27)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(27)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(27)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(27)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(26)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(26)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(26)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(26)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(26)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(26)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(26)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(26)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(26)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(26)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(26)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(26)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(26)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(26)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(26)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(26)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(25)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(25)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(25)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(25)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(25)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(25)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(25)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(25)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(25)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(25)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(25)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(25)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(25)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(25)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(25)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(25)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(24)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(24)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(24)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(24)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(24)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(24)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(24)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(24)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(24)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(24)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(24)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(24)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(24)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(24)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(24)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(24)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(23)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(23)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(23)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(23)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(23)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(23)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(23)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(23)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(23)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(23)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(23)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(23)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(23)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(23)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(23)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(23)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(22)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(22)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(22)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(22)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(22)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(22)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(22)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(22)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(22)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(22)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(22)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(22)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(22)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(22)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(22)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(22)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(21)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(21)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(21)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(21)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(21)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(21)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(21)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(21)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(21)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(21)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(21)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(21)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(21)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(21)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(21)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(21)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(20)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(20)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(20)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(20)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(20)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(20)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(20)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(20)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(20)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(20)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(20)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(20)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(20)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(20)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(20)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(20)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(19)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(19)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(19)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(19)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(19)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(19)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(19)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(19)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(19)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(19)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(19)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(19)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(19)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(19)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(19)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(19)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(18)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(18)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(18)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(18)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(18)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(18)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(18)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(18)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(18)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(18)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(18)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(18)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(18)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(18)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(18)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(18)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(17)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(17)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(17)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(17)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(17)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(17)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(17)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(17)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(17)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(17)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(17)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(17)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(17)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(17)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(17)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(17)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(16)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(16)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(16)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(16)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(16)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(16)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(16)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(16)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(16)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(16)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(16)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(16)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(16)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(16)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(16)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(16)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(15)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(15)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(15)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(15)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(15)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(15)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(15)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(15)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(15)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(15)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(15)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(15)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(15)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(15)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(15)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(15)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(14)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(14)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(14)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(14)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(14)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(14)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(14)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(14)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(14)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(14)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(14)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(14)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(14)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(14)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(14)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(14)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(13)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(13)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(13)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(13)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(13)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(13)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(13)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(13)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(13)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(13)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(13)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(13)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(13)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(13)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(13)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(13)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(12)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(12)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(12)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(12)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(12)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(12)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(12)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(12)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(12)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(12)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(12)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(12)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(12)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(12)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(12)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(12)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(11)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(11)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(11)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(11)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(11)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(11)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(11)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(11)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(11)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(11)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(11)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(11)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(11)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(11)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(11)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(11)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(10)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(10)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(10)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(10)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(10)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(10)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(10)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(10)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(10)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(10)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(10)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(10)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(10)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(10)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(10)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(10)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(9)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(9)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(9)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(9)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(9)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(9)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(9)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(9)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(9)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(9)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(9)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(9)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(9)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(9)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(9)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(9)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(8)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(8)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(8)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(8)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(8)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(8)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(8)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(8)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(8)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(8)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(8)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(8)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(8)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(8)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(8)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(8)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(7)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(7)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(7)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(7)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(7)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(7)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(7)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(7)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(7)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(7)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(7)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(7)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(7)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(7)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(7)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(7)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(6)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(6)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(6)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(6)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(6)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(6)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(6)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(6)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(6)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(6)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(6)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(6)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(6)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(6)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(6)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(6)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(5)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(5)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(5)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(5)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(5)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(5)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(5)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(5)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(5)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(5)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(5)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(5)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(5)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(5)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(5)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(5)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(4)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(4)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(4)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(4)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(4)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(4)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(4)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(4)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(4)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(4)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(4)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(4)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(4)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(4)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(4)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(4)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(3)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(3)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(3)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(3)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(3)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(3)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(3)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(3)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(3)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(3)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(3)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(3)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(3)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(3)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(3)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(3)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(2)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(2)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(2)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(2)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(2)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(2)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(2)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(2)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(2)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(2)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(2)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(2)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(2)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(2)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(2)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(2)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(1)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(1)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(1)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(1)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(1)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(1)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(1)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(1)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(1)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(1)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(1)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(1)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(1)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(1)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(1)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(1)/ICRX/prev_q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(0)/ICRX/clk_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(0)/ICRX/int_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(0)/ICRX/irq_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(0)/ICRX/icr_o
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(0)/ICRX/icr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(0)/ICRX/imr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(0)/ICRX/ier_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(0)/ICRX/itr_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(0)/ICRX/we_i
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(0)/ICRX/rising
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(0)/ICRX/falling
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(0)/ICRX/level
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(0)/ICRX/set
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(0)/ICRX/rst
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(0)/ICRX/q
add wave -noupdate -group lines /interrupt_regs_tb/regs/icr_generator(0)/ICRX/prev_q
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 342
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ms
update
WaveRestoreZoom {0 ps} {206251 ps}
